### ISSUE TITLE
inexistent commits failure.

### ISSUE THREAD

**Issue by bebbi** [ingydotnet/git-subrepo#360]
I get this error:
```
git-subrepo: Local repository does not contain 0240e18[.....] Try to 'git subrepo fetch packages/app' of add the '-F' flag to always fetch the latest content.
```

The stated advice doesn't help. The commit id is a local id created by git subrepo, and doesn't exist in the subrepo's git repository.

The latest subrepo log looks like this:

```
    git subrepo push --branch=fixes packages/app
    
    subrepo:
      subdir:   "packages/app"
      merged:   "0240e18"
    upstream:
      origin:   "https://mysuprepoforapp.git"
      branch:   "fixes"
      commit:   "0240e18"
    git-subrepo:
      version:  "0.4.0"
      origin:   "https://github.com/ingydotnet/git-subrepo"
      commit:   "74339e8"
```
