### ISSUE TITLE
Subrepo in GitHub actions

### ISSUE THREAD

**Issue by Jonyorker** [ingydotnet/git-subrepo#611]
Hi,

I’m having a real hard time getting subrepo working in GitHub actions.

do you have any example yaml or steps to install it in the action runner?

**Comment by admorgan** [comment]
Generally you would use

```yaml
steps:
  - uses: actions/checkout@v4
    with:
      # Repository name with owner. For example, actions/checkout
      # Default: ${{ github.repository }}
      repository: 'ingydotnet/git-subrepo'
      path: '<location that works for you>'
  - run: source <path to git-subrepo>/.rc
```

If can share your configuration I am happy to assist with integration.
